version: 0.2  
  
phases:  
  install:  
    runtime-versions:  
      docker: 18  
  pre_build:  
    commands:  
      - export ECR_URL_BACKEND=$ECR_URL_BACKEND
      - echo ${REPOSITORY_URI}
      - echo Logging in to Amazon ECR...  
      - aws --version  
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)  
      - REPOSITORY_URI=$ECR_URL_BACKEND
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)  
      - IMAGE_TAG=${COMMIT_HASH:=latest}  
  build:  
    commands:  
      - echo Build started on `date`  
      - echo Building the Docker image...  
      - docker build -t $REPOSITORY_URI:latest -f backend/Dockerfile .  
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG  
  post_build:  
    commands:  
      - echo Build completed on `date`  
      - echo Pushing the Docker images...  
      - docker push $REPOSITORY_URI:latest  
      - docker push $REPOSITORY_URI:$IMAGE_TAG  
